from __future__ import annotations

class Block:
    @property
    def start_line(self) -> int: ...
    @property
    def end_line(self) -> int: ...
    @property
    def checksum(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def block_type(self) -> str: ...

class Fingerprint:
    @property
    def filename(self) -> str: ...
    @property
    def checksums(self) -> list[int]: ...
    @property
    def file_hash(self) -> str: ...
    @property
    def mtime(self) -> float: ...
    @property
    def blocks(self) -> list[Block] | None: ...

class ChangedFiles:
    @property
    def modified(self) -> list[str]: ...
    @property
    def changed_blocks(self) -> dict[str, list[int]]: ...
    def has_changes(self) -> bool: ...
    def total_changed_blocks(self) -> int: ...

class TestExecution:
    @property
    def test_name(self) -> str: ...
    @property
    def duration(self) -> float: ...
    @property
    def failed(self) -> bool: ...
    @property
    def forced(self) -> bool: ...
    @property
    def fingerprints(self) -> list[Fingerprint]: ...

class ImportResult:
    @property
    def baseline_count(self) -> int: ...
    @property
    def test_execution_count(self) -> int: ...

class PytestDiffDatabase:
    def __init__(self, db_path: str) -> None: ...
    def save_test_execution(
        self,
        test_name: str,
        fingerprints: list[Fingerprint],
        duration: float,
        failed: bool,
        python_version: str = "3.12",
    ) -> None: ...
    def get_affected_tests(self, changed_blocks: dict[str, list[int]]) -> list[str]: ...
    def get_fingerprint(self, filename: str) -> Fingerprint | None: ...
    def clear_cache(self) -> None: ...
    def get_stats(self) -> dict[str, int]: ...
    def save_baseline_fingerprint(self, fingerprint: Fingerprint) -> None: ...
    def get_baseline_fingerprint(self, filename: str) -> Fingerprint | None: ...
    def clear_baseline(self) -> None: ...
    def import_baseline_from(self, source_db_path: str) -> ImportResult: ...
    def merge_baseline_from(self, source_db_path: str) -> ImportResult: ...
    def get_external_metadata(self, source_db_path: str, key: str) -> str | None: ...
    def set_metadata(self, key: str, value: str) -> None: ...
    def get_metadata(self, key: str) -> str | None: ...
    def close(self) -> None: ...

class FingerprintCache:
    def __init__(self, max_size: int | None = None) -> None: ...
    def get_or_calculate(self, path: str) -> Fingerprint: ...
    def clear(self) -> None: ...
    def stats(self) -> tuple[int, int, float]: ...
    def size(self) -> int: ...
    def max_size(self) -> int: ...

def calculate_fingerprint(path: str) -> Fingerprint: ...
def detect_changes(db_path: str, project_root: str, scope_paths: list[str]) -> ChangedFiles: ...
def process_coverage_data(
    coverage_data: dict[str, list[int]],
    project_root: str,
    test_file: str,
    verbose: bool,
    scope_paths: list[str],
    cache: FingerprintCache | None = None,
) -> list[Fingerprint]: ...
def save_baseline(
    db_path: str,
    project_root: str,
    verbose: bool,
    scope_paths: list[str],
    force: bool = False,
) -> int: ...
def parse_module(source: str) -> list[Block]: ...
